
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432
  username: postgres
  password: Admin123
  

development:
  <<: *default
  database: tastybites_development


test:
  <<: *default
  database: tastybites_test


production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
